name: My-GitHub-Action-Basics
env:
  APPLICATION_NAME      : "MyApplication"
  DEPLOY_PACKAGE_NAME   : "MyPackage-${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  my_testing:

    env:
      var1: "This is job variable 1"
      var2: "This is job variable 2"

    runs-on: ubuntu-latest1

    steps:

    - name: Print vars
      run: |
        echo "var1 = ${{env.var1}}"
        echo "var2 = ${{env.var2}}"
        echo "step var = $stepVar1"

      env:
        stepVar1: "This is step variable"

    - name: Print Hello Message in Testing
      run: echo "Hello World from Testing job"

    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run: ls -la
    
    - name: Git clone my repository
      uses: actions/checkout@v1

    - name: List current folder
      run: ls -la

    - name:
      run: java -version
        
  
  my_deploy:
    runs-on: ubuntu-latest

    needs: my_testing

    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello World from Deploy job"

    - name: Deployment
      run: |
        echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        pwd
