name: My-GitHub-Action-Basics

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: echo "Hello World1"
        
  
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run: echo "Hello World2"
